
spring:
  main:
    allow-circular-references: true

dubbo:
  protocol:
    name: dubbo
    port: 12345
  scan:
    basePackages: com.example
  application:
    name: dubbo-comsumer-demo
  registry:
    address: zookeeper://localhost:2181

hmily:
  support:
    rpc:
      annotation: true